# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
import time


class TestDeleteMember():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_deletemember(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.set_window_size(1854, 1048)
        self.driver.find_element(By.CSS_SELECTOR, ".nav-link:nth-child(1)").click()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
        self.driver.find_element(By.ID, "password").send_keys("1234")
        self.driver.find_element(By.ID, "submit").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navbar").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navbar").click()
        self.driver.find_element(By.CSS_SELECTOR, ".sidebar-toggle").click()
        self.driver.find_element(By.CSS_SELECTOR, ".sidebar-item:nth-child(7) .align-middle:nth-child(2)").click()
        time.sleep(0.2)
        self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(3) .card-body").click()
        self.driver.find_element(By.LINK_TEXT, "View Members").click()
        time.sleep(0.2)
        self.driver.find_element(By.CSS_SELECTOR, ".btn-danger").click()
