"""new_migration

Revision ID: bba2e02ea5a0
Revises: cd7c84724a05
Create Date: 2024-12-16 19:06:41.769487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba2e02ea5a0'
down_revision = 'cd7c84724a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_model_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fm_meta_data_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('rated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fm_meta_data_id'], ['fm_meta_data.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fm_meta_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fm_meta_data', schema=None) as batch_op:
        batch_op.drop_column('rating')

    op.drop_table('feature_model_rating')
    # ### end Alembic commands ###
