"""new_migration

Revision ID: cd7c84724a05
Revises: 5e257a80f7d2
Create Date: 2024-12-12 17:58:18.846486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7c84724a05'
down_revision = '5e257a80f7d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_by_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['admin_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('admin_by_id')

    # ### end Alembic commands ###
